### ISSUE TITLE
Parser proxy

### ISSUE THREAD

**Issue by INotDev** [assnctr/unfx-proxy-checker#4]
Hey. In the next version, I would like to see a tab for parsing proxies by links and automatically moving after parsing to the validation tab!
--------------------------------------------------------------------------------------------------------------
Привет. Хотелось бы в следующей версии увидеть вкладку для парсинга прокси по ссылкам и автоматическому перемещению после парсинга во вкладку проверки на валидность!

**Comment by assnctr** [comment]
Я думаю парсер не прикручивать пока, раньше хотел, сейчас точно не буду.
